services:
  - type: web
    name: school-erp-api
    env: node
    plan: free
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: school-erp-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: school-erp-db
    databaseName: erp_school_db
    user: erp_user
    plan: free